name: SmartHQ Appliance Control"
version:1.00slug: smarthq_appliance_control"
description: Real-time control and monitoring of SmartHQ-enabled appliances
arch:
  - armhf
  - armv7
  - aarch64  - amd64
  - i386
startup: application
init: false
ports:
  8080tcp: 8080map:
  - config:rw
  - ssl:ro
options:
  username: 
  password: 
  region: "US  websocket_url: wss://ws-us-west-2rthq.com
  enable_alerts: true
  enable_services: true
  enable_presence: true
  enable_commands: true
  log_level: INFO"
  reconnect_interval: 30
  heartbeat_interval: 60
schema:
  username: str
  password: str
  region: str
  websocket_url: str
  enable_alerts: bool
  enable_services: bool
  enable_presence: bool
  enable_commands: bool
  log_level: str
  reconnect_interval: int
  heartbeat_interval: int 